import * as THREE from "three";
const DEG2RAD = Math.PI / 180;
export const CAMERA_CONFIG = { rotationSensitivity: .5, zoomSensitivity: .02, panSensitivity: .014, minRadius: 5, maxRadius: 30, minElevation: 28, maxElevation: 72, panLimit: 10 } as const;
export class CameraRig {
  readonly camera: THREE.PerspectiveCamera; private readonly target = new THREE.Vector3(0, .25, 0); private radius = 18; private azimuth = 225; private elevation = 50;
  constructor(private readonly element: HTMLCanvasElement) { this.camera = new THREE.PerspectiveCamera(42, 1, .05, 150); element.addEventListener("contextmenu", this.preventContextMenu); element.addEventListener("pointermove", this.onPointerMove); element.addEventListener("wheel", this.onWheel, { passive: false }); this.updateCamera(); }
  resize(width: number, height: number): void { this.camera.aspect = width / Math.max(height, 1); this.camera.updateProjectionMatrix(); }
  dispose(): void { this.element.removeEventListener("contextmenu", this.preventContextMenu); this.element.removeEventListener("pointermove", this.onPointerMove); this.element.removeEventListener("wheel", this.onWheel); }
  private readonly preventContextMenu = (event: MouseEvent): void => event.preventDefault();
  private readonly onPointerMove = (event: PointerEvent): void => { if ((event.buttons & 2) === 0) return; if (event.ctrlKey) { const up = new THREE.Vector3(0, 1, 0); const forward = new THREE.Vector3(0, 0, 1).applyAxisAngle(up, this.azimuth * DEG2RAD); const left = new THREE.Vector3(1, 0, 0).applyAxisAngle(up, this.azimuth * DEG2RAD); this.target.addScaledVector(forward, event.movementY * CAMERA_CONFIG.panSensitivity); this.target.addScaledVector(left, event.movementX * CAMERA_CONFIG.panSensitivity); this.target.x = THREE.MathUtils.clamp(this.target.x, -CAMERA_CONFIG.panLimit, CAMERA_CONFIG.panLimit); this.target.z = THREE.MathUtils.clamp(this.target.z, -CAMERA_CONFIG.panLimit, CAMERA_CONFIG.panLimit); } else { this.azimuth -= event.movementX * CAMERA_CONFIG.rotationSensitivity; this.elevation = THREE.MathUtils.clamp(this.elevation + event.movementY * CAMERA_CONFIG.rotationSensitivity, CAMERA_CONFIG.minElevation, CAMERA_CONFIG.maxElevation); } this.updateCamera(); };
  private readonly onWheel = (event: WheelEvent): void => { event.preventDefault(); const factor = Math.exp(event.deltaY * CAMERA_CONFIG.zoomSensitivity * .05); this.radius = THREE.MathUtils.clamp(this.radius * factor, CAMERA_CONFIG.minRadius, CAMERA_CONFIG.maxRadius); this.updateCamera(); };
  private updateCamera(): void { const azimuth = this.azimuth * DEG2RAD; const elevation = this.elevation * DEG2RAD; const horizontal = this.radius * Math.cos(elevation); this.camera.position.set(this.target.x + horizontal * Math.sin(azimuth), this.target.y + this.radius * Math.sin(elevation), this.target.z + horizontal * Math.cos(azimuth)); this.camera.lookAt(this.target); this.camera.updateMatrixWorld(); }
}
